stadt-bielefeld/bielefeldGEOCLIENT

- LICENSE
This adds the copyright owner to the license
> Add copyright owner

- munimap/templates/munimap/app/ng-templates/catalog.html
Adds the catalog sorting implemented in https://github.com/terrestris/anol/pull/33
> Add catalog sorting

- munimap/static/sass/components/_geoeditor.sass
- munimap/static/sass/main.sass
- munimap/templates/munimap/app/map.html
- munimap/templates/munimap/app/ng-templates/geoeditor-draw.html
tooltips in btn groups.
labels for draw and drawer.
> Geoeditor cosmetics

- munimap/static/sass/components/_geoeditor.sass
- munimap/templates/munimap/app/ng-templates/draw.html
- munimap/templates/munimap/app/ng-templates/geoeditor-draw.html
- munimap_digitize/munimap_digitize/templates/digitize/app/ng-templates/draw.html
it is now possible to click on remove and then click the feature that should be removed.
pressed buttons have now a clean active state.
> change remove workflow.

- munimap/templates/munimap/app/ng-templates/searchbox.html
`geocoders` are now called `geocoderConfigs`.
> refactor some functionality.

- munimap/static/js/admin/admin.js
- munimap/static/js/geoeditor/geoeditor-draw-controller.js
- munimap/static/js/static-app.js
- munimap/static/sass/components/_geoeditor.sass
- munimap/templates/munimap/app/index.html
- munimap/templates/munimap/app/ng-templates/catalog.html
- munimap/templates/munimap/base.html
- munimap_digitize/munimap_digitize/static/js/app.js
- munimap_digitize/munimap_digitize/static/js/static-digitize-app.js
- munimap_transport/munimap_transport/static/js/app.js
- webpack.config.js
> Geoeditor fixes

- munimap/views/munimap.py
> add trailing slash to catalog request

- munimap/static/js/alkis/selection.js
by making use of newly introduced anol removeSystemLayer method
depends on https://github.com/terrestris/anol/pull/84
> fix alkis selection highlight bug

- Dockerfile
- docker/docker-compose.yml
- munimap/application.py
- munimap/queue/queue.py
- munimap/queue/worker.py
Some fixes for the containerize branch
> Containerize fixes

- munimap/export/mapfish.py
> fix: fix custom print

- docker/munimap-docs/source/javascript-plugins.rst
- munimap/static/js/modules/postmessage-service.js
add several services and entire openlayers object to the postmessage context. please review @jansule
> add services to postmessage context

- Dockerfile
> fix: set proper JAVA_HOME variable in Dockerfile

- munimap/stats/stats.py
> fix: use empty string instead of None for empty content-length

- munimap/application.py
- munimap/transfer.py
- munimap/views/admin.py
- munimap/views/munimap.py
- munimap_transport/munimap_transport/queries.py
- munimap_transport/munimap_transport/views/transport.py
This fixes some typos and whitespace errors. This does not include any functional changes.
> fix: fix some typos and whitespace errors

- munimap/static/sass/digitize.sass
> fix(digitize): fix css for checkbox

- munimap/model/feature.py
- munimap/query/pq.py
This fixes the printing of digitize layers and changes annotations of classmethod to staticmethod, where cls was not used.
> fix: fix printing of digitize layers

- munimap/static/js/modules/datepicker.js
- appends datepicker to body
- sets button texts to german (proper translation handling might come in the future, but requires little more efforts)
> fix: adjust date picker in digitize popup

- munimap/static/js/base-controller.js
This unpacks formValues when downloading a GeoJSON via the draw component. This is needed when first importing a GeoJSON from GEOEditor and then downloading the imported GeoJSON via the draw component.
> fix: unpack formValues when downloading geojson from draw component

- munimap/model/feature.py
- munimap/static/js/modules/plaintext.js
- munimap/static/sass/digitize.sass
- munimap/static/translations/de_DE.js
- adds the timestamp to the digitize popups
- adjusts the remove geometry button
> Digitize adjustments

- munimap_transport/munimap_transport/templates/transport/app/index.html
This fixes the loading of tours in the transport app.
> fix: loading of tours in transport app

- munimap/alkis.py
This adds a typecheck for the alkis session value.
> fix: handle alkis info session object

- dev/README.md
- dev/configs/alembic.ini
- dev/configs/munimap.conf
- dev/requirements.txt
- docker/docker-compose.yml
This MR fixes the Readme and some dev-setup requirements.
> Fix dev setup

- .github/workflows/publish.yml
- munimap/static/js/alkis/official.js
- munimap/static/js/alkis/pdf.js
- munimap/static/js/alkis/selection.js
- munimap/static/js/alkis/simple.js
- munimap/static/js/base-config.js
- munimap/static/js/base-controller.js
- munimap/static/js/digitize/digitize-controller.js
- munimap/static/sass/components/_map.sass
- package-lock.json
- package.json
This upgrades to ol@10 and ol-ext@4
> ol + ol-ext upgrade

- dev/configs/munimap.conf
- docker/docker-compose.yml
- munimap/export/mapfish.py
- munimap/layers.py
This PR adds code that passes configured styles form the layer conf to mapfish print
> fix: pass styles to mapfish print

- munimap/templates/munimap/app/index.html
This PR fixes the digitize tool by reintroducing the method `setActiveLayer()`.
Please review @jansule
> fix: digitize

- munimap/frontend/css/anol.css
title says it all...
depends on https://github.com/terrestris/anol/pull/136
> fix: improve css of feature-properties popup

- munimap/frontend/sass/appStyle.sass
- munimap/frontend/sass/helpers/mixins.sass
> fix: allow selecting text in anol-feature-properties
