stadt-bielefeld/bielefeldGEOCLIENT

munimap/helper.py, munimap/static/js/base-controller.js, munimap/static/js/draw-layer-config.js, munimap/static/js/geoeditor/geoeditor-draw-controller.js, munimap/static/js/geoeditor/geoeditor-popup-controller.js, munimap/static/js/geoeditor/geoeditor-validation-service.js, munimap/static/sass/components/_geoeditor.sass, munimap/templates/munimap/app/geoeditor-popup.html, munimap/templates/munimap/app/map.html, munimap/templates/munimap/app/ng-templates/geoeditor-draw.html, munimap/translations/de/LC_MESSAGES/messages.po, munimap/translations/messages.pot
Makes geoeditor configurable through default config.
For this the config was moved out of `componentes.geoeditor` to the root. This means that **ALL** applications using geoeditor need to be adjusted accordingly.
```yaml
components:
geoeditor:
config: 'value'
```
becomes
```yaml
components:
geoeditor: true
geoeditor:
config: 'value'
```
=> Mobile geoeditor configurability

package.json, webpack.config.js
Previously, the bundle size was quite big due to duplicate dependencies between this repo and `anol`.
This MR sets aliases for the biggest dependencies so that webpack only bundles them once.
This reduces the parsed bundle size by ~6mb.
=> reduce bundle size by deduping dependencies

munimap/views/munimap.py
By default, flask redirects requests without trailing slash to the same request with trailing slash, when the route definition itself ends with a slash.
This PR avoids the redirect by removing the trailing slash on the route definition for catalog layers/groups.
=> avoid redirects when requesting catalog groups

munimap/templates/munimap/app/index.html, munimap/views/munimap.py
- adds cache-control headers to avoid breaking page when reopening browser with opened application tab
- removes hidden unicode character
- removes trailing slash on `/app/<config>` to prevent redirect
=> Cache-Control, Hidden Unicode Character, Trailing Slash on Route

munimap/static/js/modules/postmessage-service.js
If the application was not opened by another website (e.g. iFrame), `$window.opener` is `undefined` instead of `null` in IE11, which causes a follow-up error. This PR fixes this by adding a check for `undefined`.
https://developer.mozilla.org/en-US/docs/Web/API/Window/opener
=> Fix postMessage error in IE11

munimap/helper.py, munimap/views/munimap.py
This preserves the specified layer order for groups that are listed in a map configuration.
Before, protected layers were put on top of other layers.
Also added trailing slash to `/app/<config>` endpoint.
=> Preserve layer order for groups in map config

munimap/static/js/base-controller.js
This fixes the draw import by replacing the already removed method `PermalinkService.setPermalinkParameters` with `PermalinkServer.applyPermalinkParameters`
=> fix draw import

docs/source/layers-config.rst, munimap/app_layers_def.py, munimap/layers.py, munimap/static/js/base-controller.js, munimap/templates/munimap/macros/layers.html, munimap/validation.py
This allows listing those layers within a group that should be visible by default.
Depends on https://github.com/terrestris/anol/pull/80
=> Add handling for defaultVisibleLayers config option

munimap/application.py
This PR enables stream loggers so any error is also shown in the standard output. By default both stream and file loggers are on. The config value `LOG_MODE` can be set to `BOTH`, `FILES` and `STDOUT` to enable only one or both explicitly.
=> feat: enable stream loggers

munimap/static/js/alkis/official.js, munimap/static/js/alkis/selection.js
title says it all...
This prevents popupUrl from being undefined, when called via alkis selection.
=> share popupUrl between selection and official directive

munimap_transport/munimap_transport/static/js/layers.js, munimap_transport/munimap_transport/static/js/transport-controller.js
This fixes the use of excludePopupLayers and thereby the opening of unwanted popups for the transport layers.
This also removes the transport layers from the url by adding them as systemlayers.
depends on https://github.com/terrestris/anol/pull/85
=> add transport layers as system layers and fix usage of excludePopupLayers

.github/workflows/gh-pages.yml
This should fix the pipeline for updating gh-pages by adjusting the path to the docs folder.
=> update paths to docs folder in github actions

setup.py
This sets fixed versions for the transitive dependencies `babel` and `pytz`. This is needed since `flask-babel` accepts a version range for its dependencies that includes breaking changes.
=> Set fixed versions for transitive deps babel and pytz

Dockerfile
This will concat all `*.pem` certificates mounted in `/certs` to allow setting local CAs.
=> Concat local ca certificates

Dockerfile
This includes an `apt-get upgrade -y` to keep the system up-to-date when building image.
=> include upgrading system on build

munimap/svg/mapserv.py
=> fix: fix parsing of XML in SVG export

munimap/export/mapfish.py, munimap/index/pdf.py, munimap/views/vector.py
This fixes exporting the street index when printing.
=> fix: export street index

munimap/application.py, munimap/config.py, munimap/stats/__init__.py, munimap/stats/stats.py, munimap/views/munimap.py
This adds custom logging for layer stats.
- logs stats into dedicated log file
- configurable log rotation
- configurable whitelist of URLs to log stats for
Example log:
```
DATE:2023-07-27 13:21:44,852 USER:my-user DEPARTMENT:my-department APP:my-app IP:172.0.0.10 URL:http://localhost/mapproxy/wmts/my-layer/utm32_adv/8/107/107.png STATUS:200 CONTENT-LENGTH:115119 HOST:localhost REFERER:http://localhost/app/my-app/ USER-AGENT:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 
```
=> feat: log layer stats

munimap/stats/stats.py
This adds a check for not-logged-in users and does not print stats for them
=> fix: ignore anonymous user when printing stats

munimap/stats/stats.py
This uses the first IP address in the x-forwarded-for header, to retrieve the client ip
=> fix: use x-forwarded-for for retrieving IP address

munimap/config.py, munimap/stats/stats.py, munimap/views/munimap.py
This logs the stats for the apps and catalog endpoints. This also modifies the stat-logging approach by using a decorator (`@log_stats`) instead of calling the logger within the function. This also replaces `None` values in the logs with empty strings, which leads to more compact log lines.
I had to minimally refactor the `wmts_proxy` logic for easier handling of the logger.
=> feat: log stats for catalog endpoints

munimap/application.py, munimap/transfer.py, munimap/views/admin.py, munimap/views/munimap.py, munimap_transport/munimap_transport/queries.py, munimap_transport/munimap_transport/views/transport.py
This replaces the approach of setting `current_app.layer_protection_change = True` with `touch_last_changes_file()`. Both approaches are being used to trigger reloading of the layer configurations into the app state. We had to remove the former approach, as it leads to inconsistent states between the worker instances, as these all have their own `current_app` instances. The latter approach works, because there, we make changes on the filesystem, which will have consistent state across the workers.
I also removed `touch_last_changes_file()` on places where it does not make sense to actually call it. These were probably copy and paste errors.
Depends on https://github.com/stadt-bielefeld/bielefeldGEOCLIENT/pull/98
=> Touch last changes file

munimap/views/admin.py
This adds missing `/` to admin routes. Without this `/`, the routes were merged with the parent name, i.e. `admingroups/user/remove` instead of `admin/groups/user/remove`, ...
Due to the usage of `url_for()` other parts of the application do not need to be updated.
=> fix: add missing / to admin routes

docker/munimap-docs/source/default-config.rst, munimap/static/js/geoeditor/geoeditor-draw-controller.js, package.json
This flattens the properties in the exported geojson of the geoeditor.
=> feat(geoeditor): flatten properties of exported geojson

munimap/static/js/digitize/digitize-controller.js
This adds a missing NP check for the click event that opens the digitize-popup
=> fix: add NP check to map singleclick event for digitize-popup

munimap/views/digitize.py
This removes unused code from the digitize views
=> refactor: remove unneeded functions in digitze backend

munimap/static/js/digitize/digitize-popup-controller.js, munimap/templates/munimap/app/digitize-popup.html
In a previous change, popups for newly created features did not show any content. The content was shown only, when opening the popup twice.
This fixes this behaviour. As part of that, I also removed the `ng-controller="popupController"` from the digitize popup, since this references the draw-popup-controller.
Now, we should have a clean and isolated behavior for our popup.
=> fix: fix handling of digitize feature popup

munimap/views/digitize.py
This makes use of the application wide error handling by just returning an error code instead of redirecting to another page. This allows for more consistent error handling.
=> fix: use application error handling

docker/munimap-docs/source/default-config.rst, munimap/static/js/base-config.js, munimap/static/js/geoeditor/geoeditor-popup-controller.js, munimap/static/js/modules/datepicker.js, munimap/static/js/munimap-config.js, munimap/static/sass/components/_geoeditor.sass, munimap/static/sass/digitize.sass
This updates the datepicker plugin and makes use of the anol datepicker introduced in https://github.com/jansule/anol/pull/12.
This also fixes the css for the geoditor form checkbox.
=> fix: refactor datepicker and harmonize geoeditor

munimap_digitize/munimap_digitize/views/admin.py
This adds the endpoint `/digitize/admin/migrations`, which lists the new yaml format for the digitize layers. This endpoint can be used to put the currently existing digitize layers into any layer yaml.
Please note: Due to the previous layer allowing multiple geometry types per featurecollection, there might be layers with multiple `geom_type`s. These have to be resolved to a single type in order to properly work in the future. Multiple values were only added in order to indicate layers with geometries of multiple types.
Example output:
```
layers:
- name: test_layer
source:
name: test_layer
geom_type: LineString,Point
properties:
- label: Baustelle
name: name
type: text
- label: Beschreibung
name: description
type: text
srs: EPSG:25832
style:
fillColor: '#fff'
fillOpacity: 0.4
fontColor: …
```
=> feat: add /digitize/admin/migrations endpoint

munimap/static/js/digitize/digitize-controller.js, munimap/static/js/digitize/digitize-popup-controller.js
This hides the refresh layer button after refreshing a layer instead of hiding it after the next polling.
depends on https://github.com/terrestris/anol/pull/99
=> fix: hide refresh layer button after refreshing

munimap/config.py, munimap/transfer.py, munimap/views/api.py
This replaces the ip check of the x-forwarded-for header with a check of access tokens.
=> fix: use secrets for checking access to api

munimap/model/feature.py
This adds additional handlings for cases where the created or modified dates are null on digitize_features. This can be the case with migrated features from the previous implementation of digitize.
=> fix: handle possible null values on digitize dates

munimap/helper.py
this also removes the required_roles helper which is not used and uses functions that do not exist
=> fix: also allow projects for admins

munimap/app_layers_def.py
This should fix a rare error where the first group is not a catalog layer and `_group` is not initialized. Normally this would not cause an error, because `_group` was initialized with the group before. This most likely is wrong and could have caused unexpected behavior that was not reported, yet.
=> fix: clone group early

munimap/alkis.py, munimap/app_layers_def.py
This adds layers to the catalog list, if they were selected explicitly. In that case, it does not matter if `catalog == True`.
depends on https://github.com/stadt-bielefeld/bielefeldGEOCLIENT/pull/152
=> Gfi catalog

munimap/config.py, munimap_transport/munimap_transport/static/js/app.js, munimap_transport/munimap_transport/static/js/timetable-controller.js, munimap_transport/munimap_transport/static/js/transport-api-service.js, munimap_transport/munimap_transport/templates/transport/app/index.html, munimap_transport/munimap_transport/templates/transport/app/timetable.html
This applies changes in the mobiel app to work with the lateset transport api.
=> fix: update mobiel to support latest transport api

munimap/config.py, munimap_transport/munimap_transport/static/js/transport-api-service.js, munimap_transport/munimap_transport/templates/transport/app/index.html
This adds stopfinder priorities. Through these, it is possible to prioritize items containing one of the listed keywords for the stops returned by the stopfinder request.
=> feat: add stopfinder priorities

Dockerfile, docker/docker-compose.yml, entrypoint.sh
This stops the munimap-print-worker from running alembic since db migrations are already handled by munimap-app
=> fix: stop running alembic on munimap-print-worker

.github/workflows/publish.yml, RELEASE.md, package-lock.json, pyproject.toml
This removes the use of the ANOL_COMMIT_HASH from the publish workflow so it is only necessary to change it in the Dockerfile.
=> Anol only in dockerfile

dev/README.md, dev/configs/munimap.conf, dev/manage.py, docker/docker-compose.yml, docker/munimap-app/munimap.conf, munimap/config.py, munimap/frontend/js/base-controller.js, munimap/helper.py, munimap/templates/munimap/app/index.html
This removes the application error notification from the frontend and moves it into the backend. This will cause more consistent error messages and avoids the occasionally visible notification without content.
This also includes some updates to READMEs regarding the usage of the `DEBUG` and `FLASK_DEBUG` flags.
=> Application error

munimap/frontend/sass/components/timetable.sass, munimap/frontend/sass/transport.sass
This fixes the timetable css when used in a usual app instead of mobiel / transport.
=> fix: move timetable css from transport to both app and transport

munimap/frontend/js/admin/base.js, package-lock.json, webpack.config.js
This adds the missing `worker-yaml.js` and puts it on its needed location. For some reason, this location is different from the location of the `worker-javascript.js`. So we added a separate webpack rule. We also now use the minified ace.js to save around 0.7mb.
=> fix: provide ace workers on needed locations

munimap/validation.py
This adds a first basic configuration for the new sensorthings layer.
=> feat: add initial sensorthings layer configuration/validation

munimap/query/pq.py, munimap/views/vector.py
The existing code raised errors about the input being a `str` instead of `bytes`. Using the `StringIO` class instead of the `BytesIO` class solves this problem.
=> fix: use StringIO class instead of BytesIO

munimap/model/mb_user.py
The `uselist=False,` parameter marked this as a one-to-one relation which caused errors when deleting users with more then one password_recovery request.
=> Cascade delete email verification

munimap/views/vector.py
This removes the explicit encoding of the feature name in the csv export endpoint. This leads to creating proper strings instead of having byte strings (`b'some text'`).
=> fix: remove encoding of csv export

dev/configs/logging.yaml, munimap/logging.yaml
This adjusts the stats logging config for the dev setup. There, we also use the StreamHandler now and write to stdout.
=> chore: adjust stats logging for dev setup

munimap/app_layers_def.py
This PR only sets the groups in `defaultOverlays` visible at the start of the application.
Before also the layers in `defaultVisibleLayers` would be visible at the start of the application, which is not desired.
Please review @jansule
=> fix: set defaultVisibleLayers not visible at start

munimap/app_layers_def.py
we have to set the urls for postgis/dynamic_geojson layers after trying to hash the urls, otherwise they will be reset to `None`.
=> fix: provide url for postgis/dynamic_geojson layers
